/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uml1.Interface;

import java.text.ParseException;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.plaf.basic.BasicBorders;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author batista
 */
public class FrameCad extends javax.swing.JFrame {

    /**
     * Creates new form FrameCad
     */
    public FrameCad() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        JRadioAluno = new javax.swing.JRadioButton();
        jRadioEmpregado = new javax.swing.JRadioButton();
        jRadioGerente = new javax.swing.JRadioButton();
        jRadioComissionado = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelMensalidade_sal = new javax.swing.JLabel();
        jTextFieldMensalidade_sal = new javax.swing.JTextField();
        jLabelMatricula_grat_comissa_sal = new javax.swing.JLabel();
        jTextFieldMatricula_Gratifi_Comissao_sal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CADASTRO");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(JRadioAluno);
        JRadioAluno.setText("Aluno");
        JRadioAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRadioAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(JRadioAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        buttonGroup1.add(jRadioEmpregado);
        jRadioEmpregado.setText("Empregado");
        jRadioEmpregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioEmpregadoActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioEmpregado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        buttonGroup1.add(jRadioGerente);
        jRadioGerente.setText("Gerente");
        jRadioGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioGerenteActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        buttonGroup1.add(jRadioComissionado);
        jRadioComissionado.setText("Comissionado");
        jRadioComissionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioComissionadoActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioComissionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLabel1.setText("Informe o Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        getContentPane().add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 320, -1));

        jLabel2.setText("Informe o CPF:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jFormattedTextFieldCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCPFActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Gravar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 340, 40));

        jLabelMensalidade_sal.setText("Informe a Mensalidade:");
        getContentPane().add(jLabelMensalidade_sal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        getContentPane().add(jTextFieldMensalidade_sal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 90, -1));

        jLabelMatricula_grat_comissa_sal.setText("Informe a Matricula:");
        getContentPane().add(jLabelMatricula_grat_comissa_sal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));
        getContentPane().add(jTextFieldMatricula_Gratifi_Comissao_sal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 160, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (JRadioAluno.isSelected()) {
            uml1.Controle.Controle.addAluno(jTextFieldNome.getText(), jFormattedTextFieldCPF.getText(), Integer.parseInt(jTextFieldMatricula_Gratifi_Comissao_sal.getText()), Integer.parseInt(jTextFieldMensalidade_sal.getText()));
        } else if (jRadioEmpregado.isSelected()) {
            uml1.Controle.Controle.addEmpregado(jTextFieldNome.getText(), jFormattedTextFieldCPF.getText(), Double.parseDouble(jTextFieldMatricula_Gratifi_Comissao_sal.getText()));
        } else if (jRadioGerente.isSelected()) {
            uml1.Controle.Controle.addGerente(jTextFieldNome.getText(), jFormattedTextFieldCPF.getText(), Double.parseDouble(jTextFieldMensalidade_sal.getText()), Double.parseDouble(jTextFieldMatricula_Gratifi_Comissao_sal.getText()));
        } else if (jRadioComissionado.isSelected()) {
            uml1.Controle.Controle.addComissionado(jTextFieldNome.getText(), jFormattedTextFieldCPF.getText(), Double.parseDouble(jTextFieldMensalidade_sal.getText()), Double.parseDouble(jTextFieldMatricula_Gratifi_Comissao_sal.getText()));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JRadioAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRadioAlunoActionPerformed
        if (JRadioAluno.isSelected()) {
            jLabelMatricula_grat_comissa_sal.setText("Informe a Matricula: ");
            jLabelMensalidade_sal.setText("Informe a Mensalidade: ");
            jTextFieldMensalidade_sal.setVisible(true);
            jLabelMensalidade_sal.setVisible(true);

            jTextFieldMatricula_Gratifi_Comissao_sal.setText("");
            jTextFieldMensalidade_sal.setText("");
            jTextFieldNome.setText("");
            jFormattedTextFieldCPF.setText("");
        }
    }//GEN-LAST:event_JRadioAlunoActionPerformed

    private void jRadioGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioGerenteActionPerformed
        // TODO add your handling code here:
        if (jRadioGerente.isSelected()) {
            jLabelMatricula_grat_comissa_sal.setText("Informe a Gratificação: ");
            jLabelMensalidade_sal.setText("Informe o Salario: ");
            jLabelMensalidade_sal.setVisible(true);
            jTextFieldMensalidade_sal.setVisible(true);

            jTextFieldMatricula_Gratifi_Comissao_sal.setText("");
            jTextFieldMensalidade_sal.setText("");
            jTextFieldNome.setText("");
            jFormattedTextFieldCPF.setText("");
        }
    }//GEN-LAST:event_jRadioGerenteActionPerformed

    private void jRadioComissionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioComissionadoActionPerformed
        if (jRadioComissionado.isSelected()) {
            jLabelMatricula_grat_comissa_sal.setText("Informe o Percentual: ");
            jLabelMensalidade_sal.setText("Informe o Salario: ");
            jLabelMensalidade_sal.setVisible(true);
            jTextFieldMensalidade_sal.setVisible(true);

            jTextFieldMatricula_Gratifi_Comissao_sal.setText("");
            jTextFieldMensalidade_sal.setText("");
            jTextFieldNome.setText("");
            jFormattedTextFieldCPF.setText("");
        }
    }//GEN-LAST:event_jRadioComissionadoActionPerformed

    private void jRadioEmpregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioEmpregadoActionPerformed
        // TODO add your handling code here:
        if (jRadioEmpregado.isSelected()) {
            jLabelMatricula_grat_comissa_sal.setText("Informe o salario: ");
            jLabelMensalidade_sal.setVisible(false);
            jTextFieldMensalidade_sal.setVisible(false);

            jTextFieldMatricula_Gratifi_Comissao_sal.setText("");
            jTextFieldMensalidade_sal.setText("");
            jTextFieldNome.setText("");
            jFormattedTextFieldCPF.setText("");
        }
    }//GEN-LAST:event_jRadioEmpregadoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jFormattedTextFieldCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCPFActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         try {
            MaskFormatter formatoCpf = new MaskFormatter("###.###.###-##");
            jFormattedTextFieldCPF.setFormatterFactory(new DefaultFormatterFactory(formatoCpf));
        } catch (ParseException ex) {
            System.err.println(ex.getMessage());

        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JRadioAluno;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelMatricula_grat_comissa_sal;
    private javax.swing.JLabel jLabelMensalidade_sal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioComissionado;
    private javax.swing.JRadioButton jRadioEmpregado;
    private javax.swing.JRadioButton jRadioGerente;
    private javax.swing.JTextField jTextFieldMatricula_Gratifi_Comissao_sal;
    private javax.swing.JTextField jTextFieldMensalidade_sal;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
