/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uml1.Interface;

import java.awt.Color;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import sun.java2d.pipe.RenderBuffer;
import uml1.Aluno;

/**
 *
 * @author batista
 */
public class FrameListarAluno extends javax.swing.JFrame {

    /**
     * Creates new form FrameListar
     */
    public FrameListarAluno() {
        initComponents();
        inserirTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        JtextPesquisa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 550));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTable);
        if (jTable.getColumnModel().getColumnCount() > 0) {
            jTable.getColumnModel().getColumn(0).setMinWidth(400);
            jTable.getColumnModel().getColumn(1).setMinWidth(100);
            jTable.getColumnModel().getColumn(1).setMaxWidth(100);
            jTable.getColumnModel().getColumn(2).setMinWidth(80);
            jTable.getColumnModel().getColumn(2).setMaxWidth(80);
            jTable.getColumnModel().getColumn(3).setMinWidth(70);
            jTable.getColumnModel().getColumn(3).setMaxWidth(70);
        }

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.BorderLayout());

        JtextPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextPesquisaActionPerformed(evt);
            }
        });
        JtextPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JtextPesquisaKeyReleased(evt);
            }
        });
        jPanel1.add(JtextPesquisa, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtextPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextPesquisaActionPerformed

    private void JtextPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtextPesquisaKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        while (model.getRowCount() > 0) {//Remove as linhas da tabela 
            model.removeRow(0);
        }
        inserirTb_alunoPesquisa();//atualiza tabela 
    }//GEN-LAST:event_JtextPesquisaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameListarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameListarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameListarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameListarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameListarAluno().setVisible(true);
            }
        });
    }

    public void inserirTb_alunoPesquisa() {
        setLocationRelativeTo(null);

        jTable.getColumnModel().getColumn(0).setHeaderValue("Nome");//Colocar o titulo da coluna
        jTable.getColumnModel().getColumn(1).setHeaderValue("CPF");//Colocar o titulo da coluna
        jTable.getColumnModel().getColumn(2).setHeaderValue("Mensalidade");//Colocar o titulo da coluna
        jTable.getColumnModel().getColumn(3).setHeaderValue("Matricula");//Colocar o titulo da coluna

        jTable.setCellSelectionEnabled(false);
        jTable.setRowSelectionAllowed(true);

        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        ArrayList<Aluno> listaAluno = uml1.Controle.Controle.pesquisaAluno(JtextPesquisa.getText());

        Object[] fila = new Object[model.getColumnCount()];
        for (int i = 0; i < listaAluno.size(); i++) {
            fila[0] = listaAluno.get(i).getNome();
            fila[1] = listaAluno.get(i).getCpf();
            fila[2] = listaAluno.get(i).getMensalidade();
            fila[3] = listaAluno.get(i).getMatricula();
            model.addRow(fila);
        }
    }

    public void inserirTabela() {
        setLocationRelativeTo(null);

        jTable.getColumnModel().getColumn(0).setHeaderValue("Nome");//Colocar o titulo da coluna
        jTable.getColumnModel().getColumn(1).setHeaderValue("CPF");//Colocar o titulo da coluna
        jTable.getColumnModel().getColumn(2).setHeaderValue("Mensalidade");//Colocar o titulo da coluna
        jTable.getColumnModel().getColumn(3).setHeaderValue("Matricula");//Colocar o titulo da coluna

        jTable.setCellSelectionEnabled(false);
        jTable.setRowSelectionAllowed(true);

        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        ArrayList<Aluno> listaAluno = uml1.Controle.Controle.selectAluno();

        Object[] fila = new Object[model.getColumnCount()];
        for (int i = 0; i < listaAluno.size(); i++) {
            fila[0] = listaAluno.get(i).getNome();
            fila[1] = listaAluno.get(i).getCpf();
            fila[2] = listaAluno.get(i).getMensalidade();
            fila[3] = listaAluno.get(i).getMatricula();
            model.addRow(fila);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JtextPesquisa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
