/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uml1.Interface;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import uml1.Fornecedor;

/**
 *
 * @author batista
 */
public class FrameFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form FrameFornecedor
     */
    public FrameFornecedor() {
        initComponents();
        inserirTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFornecedor = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButtonCadastrarFornecedor = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FORNECEDOR");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CNPJ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableFornecedor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 520, 240));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCadastrarFornecedor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonCadastrarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add.png"))); // NOI18N
        jButtonCadastrarFornecedor.setText("Cadastrar");
        jButtonCadastrarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarFornecedorActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCadastrarFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 40));

        jButtonAtualizar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atualizar.png"))); // NOI18N
        jButtonAtualizar.setText("Atualizar");
        jPanel1.add(jButtonAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Excluir.png"))); // NOI18N
        jButton1.setText("Excluir");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 110, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarFornecedorActionPerformed
        // TODO add your handling code here:
        FrameFornecedorCad frameCad = new FrameFornecedorCad();
        frameCad.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarFornecedorActionPerformed

       public void inserirTabela() {
        setLocationRelativeTo(null);
        
        jTableFornecedor.getColumnModel().getColumn(0).setPreferredWidth(400);
        jTableFornecedor.getColumnModel().getColumn(1).setPreferredWidth(200);
        
        jTableFornecedor.setCellSelectionEnabled(false);
        jTableFornecedor.setRowSelectionAllowed(true);
 
        DefaultTableModel model = (DefaultTableModel) jTableFornecedor.getModel();
        ArrayList<Fornecedor> listaFornecedor = uml1.Controle.Controle.selectFornecedor();
        
        Object[] fila = new Object[model.getColumnCount()];
        for (int i = 0; i < listaFornecedor.size(); i++) {
            fila[0] = listaFornecedor.get(i).getNome();
            fila[1] = listaFornecedor.get(i).getCnpj();
            model.addRow(fila);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonCadastrarFornecedor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFornecedor;
    // End of variables declaration//GEN-END:variables
}
